function [thetaMotor,theta] = InverseKinematics(in)
%% input and constants
Qx = [1  0        0; ...
      0  cos(in(1)) -sin(in(1)); ...
      0  sin(in(1)) cos(in(1))];
Qy = [cos(in(2)) 0 -sin(in(2)); ...
      0        1 0; ...
      sin(in(2)) 0 cos(in(2));];
Qz = [cos(in(3)) -sin(in(3)) 0; ...
      sin(in(3)) cos(in(3))  0; ...
      0         0        1];
Q = Qz*Qy*Qx;
gamma = 0;beta = pi/2;
alpha1 = pi/3;alpha2 = 0.9831;
eta = [0 2*pi/3 4*pi/3];
%% 

%% inverse kinematics
v = Q*[-sin(eta(1))*sin(beta) -sin(eta(2))*sin(beta) -sin(eta(3))*sin(beta);...
       cos(eta(1))*sin(beta)  cos(eta(2))*sin(beta)  cos(eta(3))*sin(beta);...
       cos(beta)              cos(beta)              cos(beta)];

A = [(cos(alpha1)*(sin(gamma)*v(2,1)-cos(gamma)*v(3,1))-sin(alpha1)*(cos(gamma)*v(2,1)+sin(gamma)*v(3,1))-cos(alpha2)) ...
     (cos(alpha1)*(sin(gamma)*v(2,2)-cos(gamma)*v(3,2))-sin(alpha1)*(cos(gamma)*v(2,2)+sin(gamma)*v(2,3))-cos(alpha2)) ...
     (cos(alpha1)*(sin(gamma)*v(2,3)-cos(gamma)*v(3,3))-sin(alpha1)*(cos(gamma)*v(2,3)+sin(gamma)*v(3,3))-cos(alpha2))];

B = [sin(alpha1)*v(1,1) ...
     sin(alpha1)*v(1,2) ...
     sin(alpha1)*v(1,3)];

C = [(cos(alpha1)*(sin(gamma)*v(2,1)-cos(gamma)*v(3,1))+sin(alpha1)*(cos(gamma)*v(2,1)+sin(gamma)*v(3,1))-cos(alpha2)) ...
     (cos(alpha1)*(sin(gamma)*v(2,2)-cos(gamma)*v(3,2))+sin(alpha1)*(cos(gamma)*v(2,2)+sin(gamma)*v(3,2))-cos(alpha2)) ...
     (cos(alpha1)*(sin(gamma)*v(2,3)-cos(gamma)*v(3,3))+sin(alpha1)*(cos(gamma)*v(2,3)+sin(gamma)*v(3,3))-cos(alpha2))];

t = [roots([A(1) 2*B(1) C(1)]) ...
     roots([A(2) 2*B(2) C(2)]) ...
     roots([A(3) 2*B(3) C(3)])];
 
theta = real(2*[atan(t(1,1)) ...
           atan(t(2,2)) ...
           atan(t(1,3))]);

% A = [-v(1,1) ...
%      -v(1,2) ...
%      -v(1,3)];
% B = [v(2,1) ...
%      v(2,2) ...
%      v(2,3)];
% C = [(cos(alpha2)+cos(alpha1)*v(3,1))/sin(alpha1) ...
%      (cos(alpha2)+cos(alpha1)*v(3,2))/sin(alpha1) ...
%      (cos(alpha2)+cos(alpha1)*v(3,3))/sin(alpha1)];
% theta = atan2([(C(1)*A(1)+B(1)*sqrt(A(1)*A(1)+B(1)*B(1)-C(1)*C(1)))/(A(1)*A(1)+B(1)*B(1)) ...
%                (C(2)*A(2)+B(2)*sqrt(A(2)*A(2)+B(2)*B(2)-C(2)*C(2)))/(A(2)*A(2)+B(2)*B(2)) ...
%                (C(3)*A(3)+B(3)*sqrt(A(3)*A(3)+B(3)*B(3)-C(3)*C(3)))/(A(3)*A(3)+B(3)*B(3))], ...
%               [(C(1)*B(1)-A(1)*sqrt(A(1)*A(1)+B(1)*B(1)-C(1)*C(1)))/(A(1)*A(1)+B(1)*B(1)) ...
%                (C(2)*B(2)-A(2)*sqrt(A(2)*A(2)+B(2)*B(2)-C(2)*C(2)))/(A(2)*A(2)+B(2)*B(2)) ...
%                (C(3)*B(3)-A(3)*sqrt(A(3)*A(3)+B(3)*B(3)-C(3)*C(3)))/(A(3)*A(3)+B(3)*B(3))]);

thetaMotor = round([theta(1) theta(3)-2*pi/3 theta(2)+2*pi/3]*180/pi,2);
if thetaMotor(1)>0
    thetaMotor(1) = thetaMotor(1) - 50.19;
else
    thetaMotor(1) = thetaMotor(1) + 50.19;
end
thetaMotor(2) = thetaMotor(2) - 50.19;
thetaMotor(3) = thetaMotor(3) - 50.19;
for i = 1:3
    if thetaMotor(i)>180
        thetaMotor(i) = thetaMotor(i)-360;
    end
    if thetaMotor(i)<-180
        thetaMotor(i) = thetaMotor(i)+360;
    end
end
end

